# Base test matrix for Logstash plugins.

default_env:
  DOCKER_ENV: "dockerjdk21.env"

agent:
  image: "family/core-ubuntu-2204"
  provider: "gcp"
  instanceType: "n2-standard-2"
  diskSizeGb: 64

jobs:
  - group: "Unit Tests"
    steps:
      - ELASTIC_STACK_VERSION=9.current
      - ELASTIC_STACK_VERSION=9.previous
      - ELASTIC_STACK_VERSION=8.current
      - SNAPSHOT=true ELASTIC_STACK_VERSION=main
      - SNAPSHOT=true ELASTIC_STACK_VERSION=9.next
      - SNAPSHOT=true ELASTIC_STACK_VERSION=9.current
      - SNAPSHOT=true ELASTIC_STACK_VERSION=9.previous
      - SNAPSHOT=true ELASTIC_STACK_VERSION=8.current