_performance: &_performance
  install: .ci/performance/docker-setup.sh
  script: .ci/performance/docker-run.sh

# Only run performance tests if plugin has them.
# Add to your .travis.yml
# env:
#  global:
#    - HAS_PERFORMANCE_TESTS=1

stages:
- name: Test
- name: Performance
  if: env(HAS_PERFORMANCE_TESTS) == "1"

env:
  jobs:
    - ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
    - ELASTIC_STACK_VERSION=7.x
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
    - SNAPSHOT=true ELASTIC_STACK_VERSION=7.x

jobs:
- stage: Performance
  name: Performance Base-Line
  <<: *_performance
  env: ELASTIC_STACK_VERSION=7.x
- <<: *_performance
  env: ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
- <<: *_performance
  env: SNAPSHOT=true ELASTIC_STACK_VERSION=8.x DOCKER_ENV=dockerjdk21.env
